// status
export const BACKUP = 'BACKUP'
export const RESTORE = 'RESTORE'
export const AUTH = 'AUTH'
export const CHANGE_USER_NAME = 'CHANGE_USER_NAME'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const LOAD_LOCALSTORAGE = 'LOAD_LOCALSTORAGE'

// user
export const SEARCH_USERS_FETCH_SUCCESS = 'SEARCH_USERS_FETCH_SUCCESS'
export const GET_USER_FETCH_SUCCESS = 'GET_USER_FETCH_SUCCESS'

// match
export const GET_MATCH_FETCH_SUCCESS = 'GET_MATCH_FETCH_SUCCESS'
export const GET_MATCHES_FETCH_SUCCESS = 'GET_MATCHES_FETCH_SUCCESS'
export const GET_OFFSET_MATCHES_FETCH_SUCCESS = 'GET_OFFSET_MATCHES_FETCH_SUCCESS'
