// status
export const AUTH = 'AUTH'
export const CHANGE_USER_NAME = 'CHANGE_USER_NAME'
export const SELECT_USER = 'SELECT_USER'
export const LOAD_LOCALSTORAGE = 'LOAD_LOCALSTORAGE'

// user
export const GET_USERS_FETCH_SUCCESS = 'GET_USERS_FETCH_SUCCESS'

// match
export const GET_MATCH_FETCH_SUCCESS = 'GET_MATCH_FETCH_SUCCESS'
export const GET_MATCHES_FETCH_SUCCESS = 'GET_MATCHES_FETCH_SUCCESS'
export const GET_OFFSET_MATCHES_FETCH_SUCCESS = 'GET_OFFSET_MATCHES_FETCH_SUCCESS'
