export default {
    blink: {
        id: 1,
        img: 'blink_lg.png?3',
        dname: 'Blink Dagger',
        qual: 'component',
        cost: 2250,
        mc: !1,
        cd: 12,
        components: null,
        created: !1
    },
    blades_of_attack: {
        id: 2,
        img: 'blades_of_attack_lg.png?3',
        dname: 'Blades of Attack',
        qual: 'component',
        cost: 420,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    broadsword: {
        id: 3,
        img: 'broadsword_lg.png?3',
        dname: 'Broadsword',
        qual: 'component',
        cost: 1200,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    chainmail: {
        id: 4,
        img: 'chainmail_lg.png?3',
        dname: 'Chainmail',
        qual: 'component',
        cost: 550,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    claymore: {
        id: 5,
        img: 'claymore_lg.png?3',
        dname: 'Claymore',
        qual: 'component',
        cost: 1400,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    helm_of_iron_will: {
        id: 6,
        img: 'helm_of_iron_will_lg.png?3',
        dname: 'Helm of Iron Will',
        qual: 'component',
        cost: 900,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    javelin: {
        id: 7,
        img: 'javelin_lg.png?3',
        dname: 'Javelin',
        qual: 'component',
        cost: 1500,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    mithril_hammer: {
        id: 8,
        img: 'mithril_hammer_lg.png?3',
        dname: 'Mithril Hammer',
        qual: 'component',
        cost: 1600,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    platemail: {
        id: 9,
        img: 'platemail_lg.png?3',
        dname: 'Platemail',
        qual: 'secret_shop',
        cost: 1400,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    quarterstaff: {
        id: 10,
        img: 'quarterstaff_lg.png?3',
        dname: 'Quarterstaff',
        qual: 'component',
        cost: 875,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    quelling_blade: {
        id: 11,
        img: 'quelling_blade_lg.png?3',
        dname: 'Quelling Blade',
        qual: 'component',
        cost: 200,
        mc: !1,
        cd: 4,
        components: null,
        created: !1
    },
    faerie_fire: {
        id: 237,
        img: 'faerie_fire_lg.png?3',
        dname: 'Faerie Fire',
        qual: 'consumable',
        cost: 75,
        mc: !1,
        cd: 5,
        components: null,
        created: !1
    },
    infused_raindrop: {
        id: 265,
        img: 'infused_raindrop_lg.png?3',
        dname: 'Infused Raindrop',
        qual: 'component',
        cost: 225,
        mc: !1,
        cd: 7,
        components: null,
        created: !1
    },
    wind_lace: {
        id: 244,
        img: 'wind_lace_lg.png?3',
        dname: 'Wind Lace',
        qual: 'component',
        cost: 250,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    ring_of_protection: {
        id: 12,
        img: 'ring_of_protection_lg.png?3',
        dname: 'Ring of Protection',
        qual: 'component',
        cost: 175,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    stout_shield: {
        id: 182,
        img: 'stout_shield_lg.png?3',
        dname: 'Stout Shield',
        qual: 'component',
        cost: 200,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    moon_shard: {
        id: 247,
        img: 'moon_shard_lg.png?3',
        dname: 'Moon Shard',
        qual: 'common',
        cost: 4e3,
        mc: !1,
        cd: !1,
        components: ['hyperstone', 'hyperstone'],
        created: !0
    },
    gauntlets: {
        id: 13,
        img: 'gauntlets_lg.png?3',
        dname: 'Gauntlets of Strength',
        qual: 'component',
        cost: 150,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    slippers: {
        id: 14,
        img: 'slippers_lg.png?3',
        dname: 'Slippers of Agility',
        qual: 'component',
        cost: 150,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    mantle: {
        id: 15,
        img: 'mantle_lg.png?3',
        dname: 'Mantle of Intelligence',
        qual: 'component',
        cost: 150,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    branches: {
        id: 16,
        img: 'branches_lg.png?3',
        dname: 'Iron Branch',
        qual: 'component',
        cost: 50,
        mc: !1,
        cd: 0,
        components: null,
        created: !1
    },
    belt_of_strength: {
        id: 17,
        img: 'belt_of_strength_lg.png?3',
        dname: 'Belt of Strength',
        qual: 'component',
        cost: 450,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    boots_of_elves: {
        id: 18,
        img: 'boots_of_elves_lg.png?3',
        dname: 'Band of Elvenskin',
        qual: 'component',
        cost: 450,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    robe: {
        id: 19,
        img: 'robe_lg.png?3',
        dname: 'Robe of the Magi',
        qual: 'component',
        cost: 450,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    circlet: {
        id: 20,
        img: 'circlet_lg.png?3',
        dname: 'Circlet',
        qual: 'component',
        cost: 165,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    ogre_axe: {
        id: 21,
        img: 'ogre_axe_lg.png?3',
        dname: 'Ogre Club',
        qual: 'component',
        cost: 1e3,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    blade_of_alacrity: {
        id: 22,
        img: 'blade_of_alacrity_lg.png?3',
        dname: 'Blade of Alacrity',
        qual: 'component',
        cost: 1e3,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    staff_of_wizardry: {
        id: 23,
        img: 'staff_of_wizardry_lg.png?3',
        dname: 'Staff of Wizardry',
        qual: 'component',
        cost: 1e3,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    ultimate_orb: {
        id: 24,
        img: 'ultimate_orb_lg.png?3',
        dname: 'Ultimate Orb',
        qual: 'secret_shop',
        cost: 2100,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    gloves: {
        id: 25,
        img: 'gloves_lg.png?3',
        dname: 'Gloves of Haste',
        qual: 'component',
        cost: 500,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    lifesteal: {
        id: 26,
        img: 'lifesteal_lg.png?3',
        dname: 'Morbid Mask',
        qual: 'component',
        cost: 1200,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    ring_of_regen: {
        id: 27,
        img: 'ring_of_regen_lg.png?3',
        dname: 'Ring of Regen',
        qual: 'component',
        cost: 325,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    sobi_mask: {
        id: 28,
        img: 'sobi_mask_lg.png?3',
        dname: 'Sage\'s Mask',
        qual: 'component',
        cost: 325,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    boots: {
        id: 29,
        img: 'boots_lg.png?3',
        dname: 'Boots of Speed',
        qual: 'component',
        cost: 400,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    gem: {
        id: 30,
        img: 'gem_lg.png?3',
        dname: 'Gem of True Sight',
        qual: 'component',
        cost: 900,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    cloak: {
        id: 31,
        img: 'cloak_lg.png?3',
        dname: 'Cloak',
        qual: 'component',
        cost: 550,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    talisman_of_evasion: {
        id: 32,
        img: 'talisman_of_evasion_lg.png?3',
        dname: 'Talisman of Evasion',
        qual: 'secret_shop',
        cost: 1450,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    cheese: {
        id: 33,
        img: 'cheese_lg.png?3',
        dname: 'Cheese',
        qual: 'epic',
        cost: 1e3,
        mc: !1,
        cd: 40,
        components: null,
        created: !1
    },
    magic_stick: {
        id: 34,
        img: 'magic_stick_lg.png?3',
        dname: 'Magic Stick',
        qual: 'component',
        cost: 200,
        mc: !1,
        cd: 13,
        components: null,
        created: !1
    },
    magic_wand: {
        id: 36,
        img: 'magic_wand_lg.png?3',
        dname: 'Magic Wand',
        qual: 'common',
        cost: 465,
        mc: !1,
        cd: 13,
        components: ['circlet', 'branches', 'branches', 'magic_stick'],
        created: !0
    },
    ghost: {
        id: 37,
        img: 'ghost_lg.png?3',
        dname: 'Ghost Scepter',
        qual: 'component',
        cost: 1500,
        mc: !1,
        cd: 25,
        components: null,
        created: !1
    },
    clarity: {
        id: 38,
        img: 'clarity_lg.png?3',
        dname: 'Clarity',
        qual: 'consumable',
        cost: 50,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    enchanted_mango: {
        id: 216,
        img: 'enchanted_mango_lg.png?3',
        dname: 'Enchanted Mango',
        qual: 'consumable',
        cost: 110,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    flask: {
        id: 39,
        img: 'flask_lg.png?3',
        dname: 'Healing Salve',
        qual: 'consumable',
        cost: 110,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    dust: {
        id: 40,
        img: 'dust_lg.png?3',
        dname: 'Dust of Appearance',
        qual: 'consumable',
        cost: 180,
        mc: !1,
        cd: 30,
        components: null,
        created: !1
    },
    bottle: {
        id: 41,
        img: 'bottle_lg.png?3',
        dname: 'Bottle',
        qual: 'consumable',
        cost: 660,
        mc: !1,
        cd: 0,
        components: null,
        created: !1
    },
    ward_observer: {
        id: 42,
        img: 'ward_observer_lg.png?3',
        dname: 'Observer Ward',
        qual: 'consumable',
        cost: 65,
        mc: !1,
        cd: 1,
        components: null,
        created: !1
    },
    ward_sentry: {
        id: 43,
        img: 'ward_sentry_lg.png?3',
        dname: 'Sentry Ward',
        qual: 'consumable',
        cost: 200,
        mc: !1,
        cd: 1,
        components: null,
        created: !1
    },
    ward_dispenser: {
        id: 218,
        img: 'ward_dispenser_lg.png?3',
        dname: 'Observer and Sentry Wards',
        qual: 'common',
        cost: 265,
        mc: !1,
        cd: !1,
        components: ['ward_sentry', 'ward_observer'],
        created: !0
    },
    tango: {
        id: 44,
        img: 'tango_lg.png?3',
        dname: 'Tango',
        qual: 'consumable',
        cost: 125,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    tango_single: {
        id: 241,
        img: 'tango_single_lg.png?3',
        dname: 'Tango (Shared)',
        qual: 'consumable',
        cost: 30,
        mc: !1,
        cd: 60,
        components: null,
        created: !1
    },
    courier: {
        id: 45,
        img: 'courier_lg.png?3',
        dname: 'Animal Courier',
        qual: 'consumable',
        cost: 100,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    tpscroll: {
        id: 46,
        img: 'tpscroll_lg.png?3',
        dname: 'Town Portal Scroll',
        qual: 'consumable',
        cost: 50,
        mc: 75,
        cd: 70,
        components: null,
        created: !1
    },
    travel_boots: {
        id: 48,
        img: 'travel_boots_lg.png?3',
        dname: 'Boots of Travel',
        qual: 'common',
        cost: 2400,
        mc: 75,
        cd: 45,
        components: ['boots'],
        created: !0
    },
    travel_boots_2: {
        id: 220,
        img: 'travel_boots_2_lg.png?3',
        dname: 'Boots of Travel',
        qual: 'common',
        cost: 4400,
        mc: 75,
        cd: 45,
        components: ['travel_boots', 'recipe_travel_boots'],
        created: !0
    },
    phase_boots: {
        id: 50,
        img: 'phase_boots_lg.png?3',
        dname: 'Phase Boots',
        qual: 'common',
        cost: 1240,
        mc: !1,
        cd: 8,
        components: ['boots', 'blades_of_attack', 'blades_of_attack'],
        created: !0
    },
    demon_edge: {
        id: 51,
        img: 'demon_edge_lg.png?3',
        dname: 'Demon Edge',
        qual: 'secret_shop',
        cost: 2400,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    eagle: {
        id: 52,
        img: 'eagle_lg.png?3',
        dname: 'Eaglesong',
        qual: 'secret_shop',
        cost: 3200,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    reaver: {
        id: 53,
        img: 'reaver_lg.png?3',
        dname: 'Reaver',
        qual: 'secret_shop',
        cost: 3e3,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    relic: {
        id: 54,
        img: 'relic_lg.png?3',
        dname: 'Sacred Relic',
        qual: 'secret_shop',
        cost: 3800,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    hyperstone: {
        id: 55,
        img: 'hyperstone_lg.png?3',
        dname: 'Hyperstone',
        qual: 'secret_shop',
        cost: 2e3,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    ring_of_health: {
        id: 56,
        img: 'ring_of_health_lg.png?3',
        dname: 'Ring of Health',
        qual: 'component',
        cost: 850,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    void_stone: {
        id: 57,
        img: 'void_stone_lg.png?3',
        dname: 'Void Stone',
        qual: 'component',
        cost: 850,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    mystic_staff: {
        id: 58,
        img: 'mystic_staff_lg.png?3',
        dname: 'Mystic Staff',
        qual: 'secret_shop',
        cost: 2700,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    energy_booster: {
        id: 59,
        img: 'energy_booster_lg.png?3',
        dname: 'Energy Booster',
        qual: 'secret_shop',
        cost: 900,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    point_booster: {
        id: 60,
        img: 'point_booster_lg.png?3',
        dname: 'Point Booster',
        qual: 'secret_shop',
        cost: 1200,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    vitality_booster: {
        id: 61,
        img: 'vitality_booster_lg.png?3',
        dname: 'Vitality Booster',
        qual: 'secret_shop',
        cost: 1100,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    power_treads: {
        id: 63,
        img: 'power_treads_lg.png?3',
        dname: 'Power Treads',
        qual: 'common',
        cost: 1350,
        mc: !1,
        cd: !1,
        components: ['boots', 'gloves', 'belt_of_strength'],
        created: !0
    },
    hand_of_midas: {
        id: 65,
        img: 'hand_of_midas_lg.png?3',
        dname: 'Hand of Midas',
        qual: 'common',
        cost: 2050,
        mc: !1,
        cd: 100,
        components: ['gloves'],
        created: !0
    },
    oblivion_staff: {
        id: 67,
        img: 'oblivion_staff_lg.png?3',
        dname: 'Oblivion Staff',
        qual: 'common',
        cost: 1650,
        mc: !1,
        cd: !1,
        components: ['quarterstaff', 'sobi_mask', 'robe'],
        created: !0
    },
    pers: {
        id: 69,
        img: 'pers_lg.png?3',
        dname: 'Perseverance',
        qual: 'common',
        cost: 1700,
        mc: !1,
        cd: !1,
        components: ['ring_of_health', 'void_stone'],
        created: !0
    },
    poor_mans_shield: {
        id: 71,
        img: 'poor_mans_shield_lg.png?3',
        dname: 'Poor Man\'s Shield',
        qual: 'common',
        cost: 500,
        mc: !1,
        cd: !1,
        components: ['slippers', 'slippers', 'stout_shield'],
        created: !0
    },
    bracer: {
        id: 73,
        img: 'bracer_lg.png?3',
        dname: 'Bracer',
        qual: 'common',
        cost: 505,
        mc: !1,
        cd: !1,
        components: ['circlet', 'gauntlets'],
        created: !0
    },
    wraith_band: {
        id: 75,
        img: 'wraith_band_lg.png?3',
        dname: 'Wraith Band',
        qual: 'common',
        cost: 485,
        mc: !1,
        cd: !1,
        components: ['circlet', 'slippers'],
        created: !0
    },
    null_talisman: {
        id: 77,
        img: 'null_talisman_lg.png?3',
        dname: 'Null Talisman',
        qual: 'common',
        cost: 470,
        mc: !1,
        cd: !1,
        components: ['circlet', 'mantle'],
        created: !0
    },
    mekansm: {
        id: 79,
        img: 'mekansm_lg.png?3',
        dname: 'Mekansm',
        qual: 'rare',
        cost: 2275,
        mc: 225,
        cd: 65,
        components: ['headdress', 'buckler'],
        created: !0
    },
    vladmir: {
        id: 81,
        img: 'vladmir_lg.png?3',
        dname: 'Vladmir\'s Offering',
        qual: 'rare',
        cost: 2275,
        mc: !1,
        cd: !1,
        components: ['headdress', 'ring_of_basilius', 'lifesteal'],
        created: !0
    },
    flying_courier: {
        id: 84,
        img: 'flying_courier_lg.png?3',
        dname: 'Flying Courier',
        qual: 'consumable',
        cost: 150,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    buckler: {
        id: 86,
        img: 'buckler_lg.png?3',
        dname: 'Buckler',
        qual: 'rare',
        cost: 800,
        mc: 10,
        cd: 25,
        components: ['chainmail', 'branches'],
        created: !0
    },
    ring_of_basilius: {
        id: 88,
        img: 'ring_of_basilius_lg.png?3',
        dname: 'Ring of Basilius',
        qual: 'rare',
        cost: 500,
        mc: !1,
        cd: !1,
        components: ['sobi_mask', 'ring_of_protection'],
        created: !0
    },
    pipe: {
        id: 90,
        img: 'pipe_lg.png?3',
        dname: 'Pipe of Insight',
        qual: 'rare',
        cost: 3100,
        mc: 100,
        cd: 60,
        components: ['hood_of_defiance', 'headdress'],
        created: !0
    },
    urn_of_shadows: {
        id: 92,
        img: 'urn_of_shadows_lg.png?3',
        dname: 'Urn of Shadows',
        qual: 'rare',
        cost: 875,
        mc: !1,
        cd: 7,
        components: ['sobi_mask', 'gauntlets', 'gauntlets'],
        created: !0
    },
    headdress: {
        id: 94,
        img: 'headdress_lg.png?3',
        dname: 'Headdress',
        qual: 'rare',
        cost: 575,
        mc: !1,
        cd: !1,
        components: ['ring_of_regen', 'branches'],
        created: !0
    },
    sheepstick: {
        id: 96,
        img: 'sheepstick_lg.png?3',
        dname: 'Scythe of Vyse',
        qual: 'rare',
        cost: 5650,
        mc: 100,
        cd: 25,
        components: ['mystic_staff', 'ultimate_orb', 'void_stone'],
        created: !0
    },
    orchid: {
        id: 98,
        img: 'orchid_lg.png?3',
        dname: 'Orchid Malevolence',
        qual: 'rare',
        cost: 4075,
        mc: 100,
        cd: 18,
        components: ['oblivion_staff', 'oblivion_staff'],
        created: !0
    },
    bloodthorn: {
        id: 250,
        img: 'bloodthorn_lg.png?3',
        dname: 'Bloodthorn',
        qual: 'epic',
        cost: 7195,
        mc: 100,
        cd: 11,
        components: ['orchid', 'lesser_crit'],
        created: !0
    },
    echo_sabre: {
        id: 252,
        img: 'echo_sabre_lg.png?3',
        dname: 'Echo Sabre',
        qual: 'artifact',
        cost: 2650,
        mc: !1,
        cd: 5,
        components: ['ogre_axe', 'oblivion_staff'],
        created: !0
    },
    cyclone: {
        id: 100,
        img: 'cyclone_lg.png?3',
        dname: 'Eul\'s Scepter of Divinity',
        qual: 'rare',
        cost: 2750,
        mc: 175,
        cd: 23,
        components: ['staff_of_wizardry', 'void_stone', 'wind_lace'],
        created: !0
    },
    aether_lens: {
        id: 232,
        img: 'aether_lens_lg.png?3',
        dname: 'Aether Lens',
        qual: 'rare',
        cost: 2350,
        mc: !1,
        cd: !1,
        components: ['energy_booster', 'ring_of_health'],
        created: !0
    },
    force_staff: {
        id: 102,
        img: 'force_staff_lg.png?3',
        dname: 'Force Staff',
        qual: 'rare',
        cost: 2225,
        mc: 25,
        cd: 20,
        components: ['staff_of_wizardry', 'ring_of_regen'],
        created: !0
    },
    hurricane_pike: {
        id: 263,
        img: 'hurricane_pike_lg.png?3',
        dname: 'Hurricane Pike',
        qual: 'epic',
        cost: 4375,
        mc: 25,
        cd: 14,
        components: ['force_staff', 'dragon_lance'],
        created: !0
    },
    dagon: {
        id: 104,
        img: 'dagon_lg.png?3',
        dname: 'Dagon',
        qual: 'rare',
        cost: 2720,
        mc: 180,
        cd: 35,
        components: ['staff_of_wizardry', 'null_talisman'],
        created: !0
    },
    dagon_2: {
        id: 201,
        img: 'dagon_2_lg.png?3',
        dname: 'Dagon',
        qual: 'rare',
        cost: 3970,
        mc: 180,
        cd: 35,
        components: ['dagon', 'recipe_dagon'],
        created: !0
    },
    dagon_3: {
        id: 202,
        img: 'dagon_3_lg.png?3',
        dname: 'Dagon',
        qual: 'rare',
        cost: 5220,
        mc: 180,
        cd: 35,
        components: ['dagon_2', 'recipe_dagon'],
        created: !0
    },
    dagon_4: {
        id: 203,
        img: 'dagon_4_lg.png?3',
        dname: 'Dagon',
        qual: 'rare',
        cost: 6470,
        mc: 180,
        cd: 35,
        components: ['dagon_3', 'recipe_dagon'],
        created: !0
    },
    dagon_5: {
        id: 204,
        img: 'dagon_5_lg.png?3',
        dname: 'Dagon',
        qual: 'rare',
        cost: 7720,
        mc: 180,
        cd: 35,
        components: ['dagon_4', 'recipe_dagon'],
        created: !0
    },
    necronomicon: {
        id: 106,
        img: 'necronomicon_lg.png?3',
        dname: 'Necronomicon',
        qual: 'rare',
        cost: 2650,
        mc: 50,
        cd: 95,
        components: ['staff_of_wizardry', 'belt_of_strength'],
        created: !0
    },
    necronomicon_2: {
        id: 193,
        img: 'necronomicon_2_lg.png?3',
        dname: 'Necronomicon',
        qual: 'rare',
        cost: 3850,
        mc: 50,
        cd: 95,
        components: ['necronomicon', 'recipe_necronomicon'],
        created: !0
    },
    necronomicon_3: {
        id: 194,
        img: 'necronomicon_3_lg.png?3',
        dname: 'Necronomicon',
        qual: 'rare',
        cost: 5050,
        mc: 50,
        cd: 95,
        components: ['necronomicon_2', 'recipe_necronomicon'],
        created: !0
    },
    ultimate_scepter: {
        id: 108,
        img: 'ultimate_scepter_lg.png?3',
        dname: 'Aghanim\'s Scepter',
        qual: 'rare',
        cost: 4200,
        mc: !1,
        cd: !1,
        components: ['point_booster', 'staff_of_wizardry', 'ogre_axe', 'blade_of_alacrity'],
        created: !0
    },
    refresher: {
        id: 110,
        img: 'refresher_lg.png?3',
        dname: 'Refresher Orb',
        qual: 'rare',
        cost: 5200,
        mc: 375,
        cd: 195,
        components: ['pers', 'pers'],
        created: !0
    },
    assault: {
        id: 112,
        img: 'assault_lg.png?3',
        dname: 'Assault Cuirass',
        qual: 'epic',
        cost: 5250,
        mc: !1,
        cd: !1,
        components: ['platemail', 'hyperstone', 'chainmail'],
        created: !0
    },
    heart: {
        id: 114,
        img: 'heart_lg.png?3',
        dname: 'Heart of Tarrasque',
        qual: 'epic',
        cost: 5500,
        mc: !1,
        cd: 7,
        components: ['reaver', 'vitality_booster'],
        created: !0
    },
    black_king_bar: {
        id: 116,
        img: 'black_king_bar_lg.png?3',
        dname: 'Black King Bar',
        qual: 'epic',
        cost: 3975,
        mc: !1,
        cd: 80,
        components: ['ogre_axe', 'mithril_hammer'],
        created: !0
    },
    aegis: {
        id: 117,
        img: 'aegis_lg.png?3',
        dname: 'Aegis of the Immortal',
        qual: 'artifact',
        cost: 0,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    shivas_guard: {
        id: 119,
        img: 'shivas_guard_lg.png?3',
        dname: 'Shiva\'s Guard',
        qual: 'epic',
        cost: 4700,
        mc: 100,
        cd: 30,
        components: ['platemail', 'mystic_staff'],
        created: !0
    },
    bloodstone: {
        id: 121,
        img: 'bloodstone_lg.png?3',
        dname: 'Bloodstone',
        qual: 'epic',
        cost: 4900,
        mc: !1,
        cd: 300,
        components: ['soul_ring', 'soul_booster'],
        created: !0
    },
    sphere: {
        id: 123,
        img: 'sphere_lg.png?3',
        dname: 'Linken\'s Sphere',
        qual: 'epic',
        cost: 4800,
        mc: !1,
        cd: 13,
        components: ['ultimate_orb', 'pers'],
        created: !0
    },
    lotus_orb: {
        id: 226,
        img: 'lotus_orb_lg.png?3',
        dname: 'Lotus Orb',
        qual: 'epic',
        cost: 4e3,
        mc: 75,
        cd: 15,
        components: ['pers', 'platemail', 'energy_booster'],
        created: !0
    },
    vanguard: {
        id: 125,
        img: 'vanguard_lg.png?3',
        dname: 'Vanguard',
        qual: 'epic',
        cost: 2150,
        mc: !1,
        cd: !1,
        components: ['ring_of_health', 'vitality_booster', 'stout_shield'],
        created: !0
    },
    crimson_guard: {
        id: 242,
        img: 'crimson_guard_lg.png?3',
        dname: 'Crimson Guard',
        qual: 'epic',
        cost: 3550,
        mc: !1,
        cd: 46,
        components: ['vanguard', 'buckler'],
        created: !0
    },
    blade_mail: {
        id: 127,
        img: 'blade_mail_lg.png?3',
        dname: 'Blade Mail',
        qual: 'epic',
        cost: 2200,
        mc: 25,
        cd: 18,
        components: ['broadsword', 'chainmail', 'robe'],
        created: !0
    },
    soul_booster: {
        id: 129,
        img: 'soul_booster_lg.png?3',
        dname: 'Soul Booster',
        qual: 'epic',
        cost: 3200,
        mc: !1,
        cd: !1,
        components: ['vitality_booster', 'energy_booster', 'point_booster'],
        created: !0
    },
    hood_of_defiance: {
        id: 131,
        img: 'hood_of_defiance_lg.png?3',
        dname: 'Hood of Defiance',
        qual: 'epic',
        cost: 1725,
        mc: 75,
        cd: 60,
        components: ['ring_of_health', 'cloak', 'ring_of_regen'],
        created: !0
    },
    rapier: {
        id: 133,
        img: 'rapier_lg.png?3',
        dname: 'Divine Rapier',
        qual: 'epic',
        cost: 6200,
        mc: !1,
        cd: !1,
        components: ['relic', 'demon_edge'],
        created: !0
    },
    monkey_king_bar: {
        id: 135,
        img: 'monkey_king_bar_lg.png?3',
        dname: 'Monkey King Bar',
        qual: 'epic',
        cost: 5400,
        mc: !1,
        cd: !1,
        components: ['demon_edge', 'javelin', 'javelin'],
        created: !0
    },
    radiance: {
        id: 137,
        img: 'radiance_lg.png?3',
        dname: 'Radiance',
        qual: 'epic',
        cost: 5150,
        mc: !1,
        cd: !1,
        components: ['relic'],
        created: !0
    },
    butterfly: {
        id: 139,
        img: 'butterfly_lg.png?3',
        dname: 'Butterfly',
        qual: 'epic',
        cost: 5525,
        mc: !1,
        cd: 25,
        components: ['eagle', 'talisman_of_evasion', 'quarterstaff'],
        created: !0
    },
    greater_crit: {
        id: 141,
        img: 'greater_crit_lg.png?3',
        dname: 'Daedalus',
        qual: 'epic',
        cost: 5520,
        mc: !1,
        cd: !1,
        components: ['lesser_crit', 'demon_edge'],
        created: !0
    },
    basher: {
        id: 143,
        img: 'basher_lg.png?3',
        dname: 'Skull Basher',
        qual: 'epic',
        cost: 2700,
        mc: !1,
        cd: 2,
        components: ['belt_of_strength', 'javelin'],
        created: !0
    },
    bfury: {
        id: 145,
        img: 'bfury_lg.png?3',
        dname: 'Battle Fury',
        qual: 'epic',
        cost: 4500,
        mc: !1,
        cd: 4,
        components: ['broadsword', 'claymore', 'pers', 'quelling_blade'],
        created: !0
    },
    manta: {
        id: 147,
        img: 'manta_lg.png?3',
        dname: 'Manta Style',
        qual: 'epic',
        cost: 4950,
        mc: 125,
        cd: 45,
        components: ['yasha', 'ultimate_orb'],
        created: !0
    },
    lesser_crit: {
        id: 149,
        img: 'lesser_crit_lg.png?3',
        dname: 'Crystalys',
        qual: 'epic',
        cost: 2120,
        mc: !1,
        cd: !1,
        components: ['broadsword', 'blades_of_attack'],
        created: !0
    },
    dragon_lance: {
        id: 236,
        img: 'dragon_lance_lg.png?3',
        dname: 'Dragon Lance',
        qual: 'artifact',
        cost: 1900,
        mc: !1,
        cd: !1,
        components: ['ogre_axe', 'boots_of_elves', 'boots_of_elves'],
        created: !0
    },
    armlet: {
        id: 151,
        img: 'armlet_lg.png?3',
        dname: 'Armlet of Mordiggian',
        qual: 'epic',
        cost: 2370,
        mc: !1,
        cd: 0,
        components: ['helm_of_iron_will', 'gloves', 'blades_of_attack'],
        created: !0
    },
    invis_sword: {
        id: 152,
        img: 'invis_sword_lg.png?3',
        dname: 'Shadow Blade',
        qual: 'epic',
        cost: 2700,
        mc: 75,
        cd: 28,
        components: ['shadow_amulet', 'claymore'],
        created: !0
    },
    silver_edge: {
        id: 249,
        img: 'silver_edge_lg.png?3',
        dname: 'Silver Edge',
        qual: 'epic',
        cost: 5100,
        mc: 75,
        cd: 24,
        components: ['invis_sword', 'ultimate_orb'],
        created: !0
    },
    sange_and_yasha: {
        id: 154,
        img: 'sange_and_yasha_lg.png?3',
        dname: 'Sange and Yasha',
        qual: 'artifact',
        cost: 4100,
        mc: !1,
        cd: !1,
        components: ['yasha', 'sange'],
        created: !0
    },
    satanic: {
        id: 156,
        img: 'satanic_lg.png?3',
        dname: 'Satanic',
        qual: 'artifact',
        cost: 5800,
        mc: !1,
        cd: 35,
        components: ['lifesteal', 'mithril_hammer', 'reaver'],
        created: !0
    },
    mjollnir: {
        id: 158,
        img: 'mjollnir_lg.png?3',
        dname: 'Mjollnir',
        qual: 'artifact',
        cost: 5700,
        mc: 50,
        cd: 35,
        components: ['maelstrom', 'hyperstone'],
        created: !0
    },
    skadi: {
        id: 160,
        img: 'skadi_lg.png?3',
        dname: 'Eye of Skadi',
        qual: 'artifact',
        cost: 5675,
        mc: !1,
        cd: !1,
        components: ['ultimate_orb', 'ultimate_orb', 'point_booster', 'orb_of_venom'],
        created: !0
    },
    sange: {
        id: 162,
        img: 'sange_lg.png?3',
        dname: 'Sange',
        qual: 'artifact',
        cost: 2050,
        mc: !1,
        cd: !1,
        components: ['ogre_axe', 'belt_of_strength'],
        created: !0
    },
    helm_of_the_dominator: {
        id: 164,
        img: 'helm_of_the_dominator_lg.png?3',
        dname: 'Helm of the Dominator',
        qual: 'artifact',
        cost: 1800,
        mc: !1,
        cd: 60,
        components: ['gloves', 'headdress', !1],
        created: !0
    },
    maelstrom: {
        id: 166,
        img: 'maelstrom_lg.png?3',
        dname: 'Maelstrom',
        qual: 'artifact',
        cost: 2800,
        mc: !1,
        cd: !1,
        components: ['mithril_hammer', 'gloves'],
        created: !0
    },
    desolator: {
        id: 168,
        img: 'desolator_lg.png?3',
        dname: 'Desolator',
        qual: 'artifact',
        cost: 3500,
        mc: !1,
        cd: !1,
        components: ['mithril_hammer', 'mithril_hammer', 'blight_stone'],
        created: !0
    },
    yasha: {
        id: 170,
        img: 'yasha_lg.png?3',
        dname: 'Yasha',
        qual: 'artifact',
        cost: 2050,
        mc: !1,
        cd: !1,
        components: ['blade_of_alacrity', 'boots_of_elves'],
        created: !0
    },
    mask_of_madness: {
        id: 172,
        img: 'mask_of_madness_lg.png?3',
        dname: 'Mask of Madness',
        qual: 'artifact',
        cost: 1900,
        mc: 25,
        cd: 20,
        components: ['lifesteal'],
        created: !0
    },
    diffusal_blade: {
        id: 174,
        img: 'diffusal_blade_lg.png?3',
        dname: 'Diffusal Blade',
        qual: 'artifact',
        cost: 3150,
        mc: !1,
        cd: 4,
        components: ['blade_of_alacrity', 'blade_of_alacrity', 'robe'],
        created: !0
    },
    diffusal_blade_2: {
        id: 196,
        img: 'diffusal_blade_2_lg.png?3',
        dname: 'Diffusal Blade',
        qual: 'artifact',
        cost: 3850,
        mc: !1,
        cd: 4,
        components: ['diffusal_blade', 'recipe_diffusal_blade'],
        created: !0
    },
    ethereal_blade: {
        id: 176,
        img: 'ethereal_blade_lg.png?3',
        dname: 'Ethereal Blade',
        qual: 'epic',
        cost: 4700,
        mc: 100,
        cd: 20,
        components: ['eagle', 'ghost'],
        created: !0
    },
    soul_ring: {
        id: 178,
        img: 'soul_ring_lg.png?3',
        dname: 'Soul Ring',
        qual: 'common',
        cost: 800,
        mc: !1,
        cd: 30,
        components: ['ring_of_regen', 'sobi_mask'],
        created: !0
    },
    arcane_boots: {
        id: 180,
        img: 'arcane_boots_lg.png?3',
        dname: 'Arcane Boots',
        qual: 'rare',
        cost: 1300,
        mc: !1,
        cd: 55,
        components: ['boots', 'energy_booster'],
        created: !0
    },
    octarine_core: {
        id: 235,
        img: 'octarine_core_lg.png?3',
        dname: 'Octarine Core',
        qual: 'rare',
        cost: 5900,
        mc: !1,
        cd: !1,
        components: ['mystic_staff', 'soul_booster'],
        created: !0
    },
    orb_of_venom: {
        id: 181,
        img: 'orb_of_venom_lg.png?3',
        dname: 'Orb of Venom',
        qual: 'component',
        cost: 275,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    blight_stone: {
        id: 240,
        img: 'blight_stone_lg.png?3',
        dname: 'Blight Stone',
        qual: 'component',
        cost: 300,
        mc: !1,
        cd: !1,
        components: null,
        created: !1
    },
    ancient_janggo: {
        id: 185,
        img: 'ancient_janggo_lg.png?3',
        dname: 'Drum of Endurance',
        qual: 'rare',
        cost: 1780,
        mc: !1,
        cd: 30,
        components: ['sobi_mask', 'bracer', 'wind_lace'],
        created: !0
    },
    medallion_of_courage: {
        id: 187,
        img: 'medallion_of_courage_lg.png?3',
        dname: 'Medallion of Courage',
        qual: 'rare',
        cost: 1175,
        mc: !1,
        cd: 7,
        components: ['chainmail', 'sobi_mask', 'blight_stone'],
        created: !0
    },
    solar_crest: {
        id: 229,
        img: 'solar_crest_lg.png?3',
        dname: 'Solar Crest',
        qual: 'rare',
        cost: 2625,
        mc: !1,
        cd: 7,
        components: ['medallion_of_courage', 'talisman_of_evasion'],
        created: !0
    },
    smoke_of_deceit: {
        id: 188,
        img: 'smoke_of_deceit_lg.png?3',
        dname: 'Smoke of Deceit',
        qual: 'consumable',
        cost: 50,
        mc: !1,
        cd: 1,
        components: null,
        created: !1
    },
    tome_of_knowledge: {
        id: 257,
        img: 'tome_of_knowledge_lg.png?3',
        dname: 'Tome of Knowledge',
        qual: 'consumable',
        cost: 150,
        mc: !1,
        cd: 0,
        components: null,
        created: !1
    },
    veil_of_discord: {
        id: 190,
        img: 'veil_of_discord_lg.png?3',
        dname: 'Veil of Discord',
        qual: 'rare',
        cost: 2240,
        mc: 50,
        cd: 20,
        components: ['helm_of_iron_will', 'null_talisman', 'null_talisman'],
        created: !0
    },
    guardian_greaves: {
        id: 231,
        img: 'guardian_greaves_lg.png?3',
        dname: 'Guardian Greaves',
        qual: 'rare',
        cost: 5275,
        mc: !1,
        cd: 40,
        components: ['mekansm', 'arcane_boots'],
        created: !0
    },
    rod_of_atos: {
        id: 206,
        img: 'rod_of_atos_lg.png?3',
        dname: 'Rod of Atos',
        qual: 'rare',
        cost: 3100,
        mc: 50,
        cd: 16,
        components: ['vitality_booster', 'staff_of_wizardry', 'staff_of_wizardry'],
        created: !0
    },
    iron_talon: {
        id: 239,
        img: 'iron_talon_lg.png?3',
        dname: 'Iron Talon',
        qual: 'common',
        cost: 500,
        mc: !1,
        cd: 20,
        components: ['quelling_blade', 'ring_of_protection'],
        created: !0
    },
    abyssal_blade: {
        id: 208,
        img: 'abyssal_blade_lg.png?3',
        dname: 'Abyssal Blade',
        qual: 'epic',
        cost: 6400,
        mc: 75,
        cd: 35,
        components: ['basher', 'vanguard'],
        created: !0
    },
    heavens_halberd: {
        id: 210,
        img: 'heavens_halberd_lg.png?3',
        dname: 'Heaven\'s Halberd',
        qual: 'artifact',
        cost: 3500,
        mc: 100,
        cd: 30,
        components: ['sange', 'talisman_of_evasion'],
        created: !0
    },
    ring_of_aquila: {
        id: 212,
        img: 'ring_of_aquila_lg.png?3',
        dname: 'Ring of Aquila',
        qual: 'rare',
        cost: 985,
        mc: !1,
        cd: !1,
        components: ['wraith_band', 'ring_of_basilius'],
        created: !0
    },
    tranquil_boots: {
        id: 214,
        img: 'tranquil_boots_lg.png?3',
        dname: 'Tranquil Boots',
        qual: 'rare',
        cost: 900,
        mc: !1,
        cd: 13,
        components: ['boots', 'ring_of_protection', 'ring_of_regen'],
        created: !0
    },
    shadow_amulet: {
        id: 215,
        img: 'shadow_amulet_lg.png?3',
        dname: 'Shadow Amulet',
        qual: !1,
        cost: 1300,
        mc: !1,
        cd: 7,
        components: null,
        created: !1
    },
    glimmer_cape: {
        id: 254,
        img: 'glimmer_cape_lg.png?3',
        dname: 'Glimmer Cape',
        qual: 'rare',
        cost: 1850,
        mc: 90,
        cd: 14,
        components: ['shadow_amulet', 'cloak'],
        created: !0
    },
    river_painter: {
        id: 1021,
        img: 'river_painter_lg.png?3',
        dname: 'River Vial: Chrome',
        qual: 'component',
        cost: 0,
        mc: !1,
        cd: 0,
        components: null,
        created: !1
    },
    river_painter2: {
        id: 1022,
        img: 'river_painter2_lg.png?3',
        dname: 'River Vial: Dry',
        qual: 'component',
        cost: 0,
        mc: !1,
        cd: 0,
        components: null,
        created: !1
    },
    river_painter3: {
        id: 1023,
        img: 'river_painter3_lg.png?3',
        dname: 'River Vial: Slime',
        qual: 'component',
        cost: 0,
        mc: !1,
        cd: 0,
        components: null,
        created: !1
    },
    river_painter4: {
        id: 1024,
        img: 'river_painter4_lg.png?3',
        dname: 'River Vial: Oil',
        qual: 'component',
        cost: 0,
        mc: !1,
        cd: 0,
        components: null,
        created: !1
    },
    river_painter5: {
        id: 1025,
        img: 'river_painter5_lg.png?3',
        dname: 'River Vial: Electrified',
        qual: 'component',
        cost: 0,
        mc: !1,
        cd: 0,
        components: null,
        created: !1
    },
    river_painter6: {
        id: 1026,
        img: 'river_painter6_lg.png?3',
        dname: 'River Vial: Potion',
        qual: 'component',
        cost: 0,
        mc: !1,
        cd: 0,
        components: null,
        created: !1
    },
    river_painter7: {
        id: 1027,
        img: 'river_painter7_lg.png?3',
        dname: 'River Vial: Blood',
        qual: 'component',
        cost: 0,
        mc: !1,
        cd: 0,
        components: null,
        created: !1
    }
}
